export const tipoDocumentoOptions = [
    { value: "", text: "Selecciona..." },
    { value: "DNI", text: "DNI" },
    { value: "PASAPORTE", text: "Pasaporte" },
];
// src/components/Pagos/store/locations.ts

export const provinces = [
    "Buenos Aires",
    "Ciudad Autónoma de Buenos Aires",
    "Catamarca",
    "Chaco",
    "Chubut",
    "Córdoba",
    "Corrientes",
    "Entre Ríos",
    "Formosa",
    "Jujuy",
    "La Pampa",
    "La Rioja",
    "Mendoza",
    "Misiones",
    "Neuquén",
    "Río Negro",
    "Salta",
    "San Juan",
    "San Luis",
    "Santa Cruz",
    "Santa Fe",
    "Santiago del Estero",
    "Tierra del Fuego",
];

export const citiesByProvince: Record<string, { value: string; text: string }[]> = {
    "Buenos Aires": [
        { value: "La Plata", text: "La Plata" },
        { value: "Mar del Plata", text: "Mar del Plata" },
        { value: "Bahía Blanca", text: "Bahía Blanca" },
        { value: "Tandil", text: "Tandil" },
        { value: "Quilmes", text: "Quilmes" },
        { value: "Lomas de Zamora", text: "Lomas de Zamora" },
        { value: "San Isidro", text: "San Isidro" },
        { value: "Merlo", text: "Merlo" },
        { value: "San Miguel", text: "San Miguel" },
        { value: "Moreno", text: "Moreno" },
    ],
    "Ciudad Autónoma de Buenos Aires": [
        { value: "CABA", text: "Ciudad Autónoma de Buenos Aires" },
    ],
    Catamarca: [
        { value: "San Fernando del Valle de Catamarca", text: "San Fernando del Valle de Catamarca" },
        { value: "San Isidro", text: "San Isidro" },
    ],
    Chaco: [
        { value: "Resistencia", text: "Resistencia" },
        { value: "Sáenz Peña", text: "Sáenz Peña" },
    ],
    Chubut: [
        { value: "Rawson", text: "Rawson" },
        { value: "Trelew", text: "Trelew" },
        { value: "Comodoro Rivadavia", text: "Comodoro Rivadavia" },
        { value: "Puerto Madryn", text: "Puerto Madryn" },
        { value: "Esquel", text: "Esquel" },
        { value: "Gaiman", text: "Gaiman" },
        { value: "José de San Martín", text: "José de San Martín" },
        { value: "Lago Blanco", text: "Lago Blanco" },
        { value: "Lago Puelo", text: "Lago Puelo" },
        { value: "Lagunita Salada", text: "Lagunita Salada" },
        { value: "Las Plumas", text: "Las Plumas" },
        { value: "Los Altares", text: "Los Altares" },
        { value: "Paso de Indios", text: "Paso de Indios" },
        { value: "Paso del Sapo", text: "Paso del Sapo" },
        { value: "Puerto Pirámides", text: "Puerto Pirámides" },
        { value: "Rada Tilly", text: "Rada Tilly" },
        { value: "Río Mayo", text: "Río Mayo" },
        { value: "Río Pico", text: "Río Pico" },
        { value: "Sarmiento", text: "Sarmiento" },
        { value: "Tecka", text: "Tecka" },
        { value: "Telsen", text: "Telsen" },
        { value: "Trevelin", text: "Trevelin" },
        { value: "Veintiocho de Julio", text: "Veintiocho de Julio" },
    ],
    Córdoba: [
        { value: "Córdoba", text: "Córdoba" },
        { value: "Villa Carlos Paz", text: "Villa Carlos Paz" },
        { value: "Río Cuarto", text: "Río Cuarto" },
        { value: "Villa María", text: "Villa María" },
    ],
    Corrientes: [
        { value: "Corrientes", text: "Corrientes" },
        { value: "Goya", text: "Goya" },
        { value: "Alvear", text: "Alvear" },
        { value: "Bella Vista", text: "Bella Vista" },
        { value: "Curuzú Cuatiá", text: "Curuzú Cuatiá" },
        { value: "Empedrado", text: "Empedrado" },
        { value: "Esquina", text: "Esquina" },
        { value: "Gobernador Virasoro", text: "Gobernador Virasoro" },
        { value: "Itatí", text: "Itatí" },
        { value: "Ituzaingó", text: "Ituzaingó" },
        { value: "Paso de los Libres", text: "Paso de los Libres" },
        { value: "Santo Tomé", text: "Santo Tomé" },
        { value: "Saladas", text: "Saladas" },
        { value: "Santa Lucía", text: "Santa Lucía" },
        { value: "Sauce", text: "Sauce" },
    ],
    "Entre Ríos": [
        { value: "Paraná", text: "Paraná" },
        { value: "Concordia", text: "Concordia" },
        { value: "Gualeguaychú", text: "Gualeguaychú" },
        { value: "Basavilbaso", text: "Basavilbaso" },
        { value: "Chajarí", text: "Chajarí" },
        { value: "Colón", text: "Colón" },
        { value: "Concepción del Uruguay", text: "Concepción del Uruguay" },
        { value: "Crespo", text: "Crespo" },
        { value: "Diamante", text: "Diamante" },
        { value: "Federación", text: "Federación" },
        { value: "Gualeguay", text: "Gualeguay" },
        { value: "La Paz", text: "La Paz" },
        { value: "Larroque", text: "Larroque" },
        { value: "Libertador San Martín", text: "Libertador San Martín" },
        { value: "Puiggari", text: "Puiggari" },
        { value: "San José", text: "San José" },
        { value: "Urdinarrain", text: "Urdinarrain" },
        { value: "Victoria", text: "Victoria" },
        { value: "Villa Elisa", text: "Villa Elisa" },
        { value: "Villa Paranacito", text: "Villa Paranacito" },
        { value: "Villaguay", text: "Villaguay" },
    ],
    Formosa: [
        { value: "Formosa", text: "Formosa" },
        { value: "Clorinda", text: "Clorinda" },
        { value: "Ibarreta", text: "Ibarreta" },
        { value: "Las Lomitas", text: "Las Lomitas" },
        { value: "Puerto Pilcomayo", text: "Puerto Pilcomayo" },
    ],
    Jujuy: [
        { value: "San Salvador de Jujuy", text: "San Salvador de Jujuy" },
        { value: "Palpalá", text: "Palpalá" },
        { value: "General San Martín", text: "General San Martín" },
        { value: "Humahuaca", text: "Humahuaca" },
        { value: "León", text: "León" },
        { value: "La Quiaca", text: "La Quiaca" },
        { value: "San Pedro", text: "San Pedro" },
        { value: "Tilcara", text: "Tilcara" },
    ],
    "La Pampa": [
        { value: "Santa Rosa", text: "Santa Rosa" },
        { value: "General Pico", text: "General Pico" },
        { value: "Eduardo Castex", text: "Eduardo Castex" },
        { value: "Guatraché", text: "Guatraché" },
        { value: "Macachín", text: "Macachín" },
        { value: "Realicó", text: "Realicó" },
        { value: "Santa Isabel", text: "Santa Isabel" },
    ],
    "La Rioja": [
        { value: "La Rioja", text: "La Rioja" },
        { value: "Chilecito", text: "Chilecito" },
        { value: "Aimogasta", text: "Aimogasta" },
        { value: "Anillaco", text: "Anillaco" },
        { value: "Chepes", text: "Chepes" },
        { value: "El Chamical", text: "El Chamical" },
        { value: "Famatina", text: "Famatina" },
        { value: "Patquía", text: "Patquía" },
        { value: "Villa Unión", text: "Villa Unión" },
    ],
    Mendoza: [
        { value: "Mendoza", text: "Mendoza" },
        { value: "San Rafael", text: "San Rafael" },
        { value: "Godoy Cruz", text: "Godoy Cruz" },
        { value: "Las Heras", text: "Las Heras" },
        { value: "La Paz", text: "La Paz" },
        { value: "Luján de Cuyo", text: "Luján de Cuyo" },
        { value: "Malargüe", text: "Malargüe" },
        { value: "Palmira", text: "Palmira" },
        { value: "Puente del Inca", text: "Puente del Inca" },
        { value: "Punta de Vacas", text: "Punta de Vacas" },
        { value: "Rivadavia", text: "Rivadavia" },
        { value: "San Martín", text: "San Martín" },
        { value: "Tunuyán", text: "Tunuyán" },
        { value: "Tupungato", text: "Tupungato" },
        { value: "Uspallata", text: "Uspallata" },
    ],
    Misiones: [
        { value: "Posadas", text: "Posadas" },
        { value: "Oberá", text: "Oberá" },
        { value: "Eldorado", text: "Eldorado" },
        { value: "Apóstoles", text: "Apóstoles" },
        { value: "Puerto Iguazú", text: "Puerto Iguazú" },
        { value: "Andresito", text: "Andresito" },
        { value: "Bernardo de Irigoyen", text: "Bernardo de Irigoyen" },
        { value: "Candelaria", text: "Candelaria" },
        { value: "Montecarlo", text: "Montecarlo" },
        { value: "Puerto Esperanza", text: "Puerto Esperanza" },
    ],
    Neuquén: [
        { value: "Neuquén", text: "Neuquén" },
        { value: "Cutral Có", text: "Cutral Có" },
        { value: "Plottier", text: "Plottier" },
        { value: "Aluminé", text: "Aluminé" },
        { value: "Centenario", text: "Centenario" },
        { value: "Chos Malal", text: "Chos Malal" },
        { value: "Junín de los Andes", text: "Junín de los Andes" },
        { value: "Loncopué", text: "Loncopué" },
        { value: "Piedra del Águila", text: "Piedra del Águila" },
        { value: "San Martín de los Andes", text: "San Martín de los Andes" },
        { value: "Villa La Angostura", text: "Villa La Angostura" },
        { value: "Zapala", text: "Zapala" },
    ],
    "Río Negro": [
        { value: "Viedma", text: "Viedma" },
        { value: "General Roca", text: "General Roca" },
        { value: "Cipolletti", text: "Cipolletti" },
        { value: "Bariloche", text: "Bariloche" },
        { value: "Allen", text: "Allen" },
        { value: "Campo Grande", text: "Campo Grande" },
        { value: "Colonia Catriel", text: "Colonia Catriel" },
        { value: "Cervantes", text: "Cervantes" },
        { value: "Chichinales", text: "Chichinales" },
        { value: "Chimpay", text: "Chimpay" },
        { value: "Choele Choel", text: "Choele Choel" },
        { value: "Cinco Saltos", text: "Cinco Saltos" },
        { value: "Comallo", text: "Comallo" },
        { value: "Contralmirante Cordero", text: "Contralmirante Cordero" },
        { value: "Coronel Belisle", text: "Coronel Belisle" },
        { value: "Darwin", text: "Darwin" },
        { value: "Dina Huapi", text: "Dina Huapi" },
        { value: "El Bolsón", text: "El Bolsón" },
    ],
    "San Luis": [
        { value: "San Luis", text: "San Luis" },
        { value: "Villa Mercedes", text: "Villa Mercedes" },
        { value: "Merlo", text: "Merlo" },
        { value: "La Punta", text: "La Punta" },
        { value: "Juana Koslay", text: "Juana Koslay" },
        { value: "Concarán", text: "Concarán" },
        { value: "Tilisarao", text: "Tilisarao" },
        { value: "Santa Rosa del Conlara", text: "Santa Rosa del Conlara" },
    ],
    "San Juan": [
        { value: "San Juan", text: "San Juan" },
        { value: "Rivadavia", text: "Rivadavia" },
        { value: "Chimbas", text: "Chimbas" },
        { value: "Caucete", text: "Caucete" },
        { value: "Pocito", text: "Pocito" },
        { value: "Rawson", text: "Rawson" },
        { value: "Santa Lucía", text: "Santa Lucía" },
        { value: "Villa Krause", text: "Villa Krause" },
        { value: "Albardón", text: "Albardón" },
        { value: "Calingasta", text: "Calingasta" },
        { value: "Jáchal", text: "Jáchal" },
        { value: "Valle Fértil", text: "Valle Fértil" }
    ],
    "Santa Cruz": [
        { value: "Río Gallegos", text: "Río Gallegos" },
        { value: "Caleta Olivia", text: "Caleta Olivia" },
        { value: "El Calafate", text: "El Calafate" },
        { value: "Pico Truncado", text: "Pico Truncado" },
        { value: "Puerto Deseado", text: "Puerto Deseado" },
        { value: "Puerto San Julián", text: "Puerto San Julián" },
        { value: "Río Turbio", text: "Río Turbio" },
        { value: "El Chaltén", text: "El Chaltén" },
        { value: "Los Antiguos", text: "Los Antiguos" },
        { value: "Perito Moreno", text: "Perito Moreno" }
    ],
    "Santiago del Estero": [
        { value: "Santiago del Estero", text: "Santiago del Estero" },
        { value: "La Banda", text: "La Banda" },
        { value: "Añatuya", text: "Añatuya" },
        { value: "Bandera", text: "Bandera" },
        { value: "Clodomira", text: "Clodomira" },
        { value: "Frías", text: "Frías" },
        { value: "Loreto", text: "Loreto" },
        { value: "Quimilí", text: "Quimilí" },
        { value: "Termas de Río Hondo", text: "Termas de Río Hondo" },
        { value: "Villa Ojo de Agua", text: "Villa Ojo de Agua" }
    ],
    "Tierra del Fuego": [
        { value: "Ushuaia", text: "Ushuaia" },
        { value: "Río Grande", text: "Río Grande" },
        { value: "Tolhuin", text: "Tolhuin" }
    ],
    "Santa Fe": [
        { value: "Santa Fe", text: "Santa Fe" },
        { value: "Rosario", text: "Rosario" },
        { value: "Rafaela", text: "Rafaela" },
        { value: "Venado Tuerto", text: "Venado Tuerto" },
        { value: "Reconquista", text: "Reconquista" },
        { value: "Santo Tomé", text: "Santo Tomé" },
        { value: "Villa Gobernador Gálvez", text: "Villa Gobernador Gálvez" },
        { value: "San Lorenzo", text: "San Lorenzo" },
        { value: "Sunchales", text: "Sunchales" },
        { value: "Esperanza", text: "Esperanza" },
        { value: "San Justo", text: "San Justo" },
        { value: "Villa Constitución", text: "Villa Constitución" },
        { value: "San Jorge", text: "San Jorge" },
        { value: "Firmat", text: "Firmat" },
        { value: "Casilda", text: "Casilda" },
        { value: "Gálvez", text: "Gálvez" },
        { value: "Arroyo Seco", text: "Arroyo Seco" },
        { value: "Cañada de Gómez", text: "Cañada de Gómez" },
        { value: "El Trébol", text: "El Trébol" },
        { value: "Las Rosas", text: "Las Rosas" }
    ]
};

